name: MySchedule
options:
  bundleIdPrefix: com.jack
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "9B772P8622"
targets:
  MySchedule:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    entitlements:
      path: Resources/MySchedule.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jack.myschedule
    dependencies:
      - target: MyScheduleWidgetExtension
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jack.myschedule
        MARKETING_VERSION: "1.2.1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"

  MyScheduleWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - Widget
      - path: Sources/Models
        createIntermediateGroups: true
      - path: Sources/Shared
        createIntermediateGroups: true
    entitlements:
      path: Widget/MyScheduleWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jack.myschedule
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jack.myschedule.widget
        MARKETING_VERSION: "1.2.1"
        INFOPLIST_FILE: Widget/Info.plist
        CODE_SIGN_STYLE: Automatic
